"""empty message

Revision ID: 37cab33633c7
Revises: 7130fce393b4
Create Date: 2024-02-23 15:33:34.577038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37cab33633c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().dialect.has_table(op.get_bind(), "ranks"):
        # Создание таблицы departments
        op.create_table(
            'ranks',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('name', sa.String(length=128)),

            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "positions"):
        # Создание таблицы departments
        op.create_table(
            'positions',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),

            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "departments"):
        # Создание таблицы departments
        op.create_table(
            'departments',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),

            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "managements"):
        # Создание таблицы managements
        op.create_table(
            'managements',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),
            sa.Column('department_id', sa.Integer, sa.ForeignKey('departments.id')),
            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "divisions"):
        # Создание таблицы divisions
        op.create_table(
            'divisions',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),
            sa.Column('management_id', sa.Integer, sa.ForeignKey('managements.id')),
            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "statuses"):
        # Создание таблицы statuses
        op.create_table(
            'statuses',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),
            sa.Column('start_date', sa.Date, nullable=True),
            sa.Column('end_date', sa.Date, nullable=True),
            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "employers"):
        # Создание таблицы employers
        op.create_table(
            'employers',
            sa.Column('id', sa.Integer, primary_key=True, index=True),
            sa.Column('surname', sa.String(length=128), nullable=False),
            sa.Column('firstname', sa.String(length=128), nullable=False),
            sa.Column('patronymic', sa.String(length=128), nullable=True),
            sa.Column('sort', sa.Integer, nullable=False),
            sa.Column("photo", sa.String(length=1024), nullable=True),
            sa.Column("note", sa.Text, nullable=True),

            sa.Column('rank_id', sa.Integer, sa.ForeignKey('ranks.id')),
            sa.Column('division_id', sa.Integer, sa.ForeignKey('divisions.id')),
            sa.Column('status_id', sa.Integer, sa.ForeignKey('statuses.id')),
            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "states"):
        # Создание таблицы states
        op.create_table(
            'states',
            sa.Column('id', sa.Integer, primary_key=True),

            sa.Column('department_id', sa.Integer, sa.ForeignKey('departments.id')),
            sa.Column('management_id', sa.Integer, sa.ForeignKey('managements.id')),
            sa.Column('division_id', sa.Integer, sa.ForeignKey('divisions.id')),
            sa.Column('position_id', sa.Integer, sa.ForeignKey('positions.id')),
            sa.Column('employer_id', sa.Integer, sa.ForeignKey('employers.id'), nullable=True, unique=True),

            sa.Column(
                'created_at', sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                'updated_at',
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    if not op.get_bind().dialect.has_table(op.get_bind(), "users"):
        op.create_table(
            "users",
            sa.Column("id", sa.Integer, primary_key=True, index=True),
            sa.Column("email", sa.String(length=150), nullable=True, unique=True),
            sa.Column("password", sa.String(length=255), nullable=True),
            sa.Column("workplace", sa.String(length=128), nullable=True),
            sa.Column("iin", sa.String(length=12), nullable=False, unique=True),
            sa.Column("phone_number", sa.String(length=20), nullable=True),
            sa.Column("last_signed_at", sa.TIMESTAMP(timezone=True), nullable=True),
            sa.Column("login_count", sa.Integer, nullable=False, default=0),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("namekz", sa.String(length=128), nullable=True),
            sa.Column("nameen", sa.String(length=128), nullable=True),
            sa.Column("employer_id", sa.Integer(), sa.ForeignKey("employers.id"), nullable=True),
            sa.Column(
                "created_at", sa.DateTime, nullable=False, server_default=sa.func.now()
            ),
            sa.Column(
                "updated_at",
                sa.DateTime,
                nullable=False,
                server_default=sa.func.now(),
                onupdate=sa.func.now(),
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("departments")
    op.drop_table("managements")
    op.drop_table("divisions")
    op.drop_table("positions")
    op.drop_table("ranks")
    op.drop_table("statuses")
    op.drop_table("employers")
    op.drop_table("states")

    # ### end Alembic commands ###
