from .rank import rank_service
from .position import position_service
from .status import status_service
from .division import division_service
from .management import management_service
from .department import department_service
from .data_for_employers import data_service
from .user import user_service
from .employer import employer_service
from .state import state_service
from .auth import auth_service
